@startuml

class Clustering {
    + hierarchy_level: int
    + children: dict
    + _input_data: InputData
    + _fitter: Fitter
    + _predictor: Predictor
    + _labels: Labels
    + _summary: Summary
    + Clustering get_child(label)
    + _fit(cluster_params: ClusterParameters)
    + fit(radius_cutoff: int, ...)
    + fit_hierarchical(radius_cutoff: int, ...)
    + isolate()
    + reel()
    + predict()
}

class Summary {
    + _list : list
    + DataFrame to_DataFrame()
}

class Record {
    + n_points: int
    + radius_cutoff: float
    + cnn_cutoff: int
    + member_cutoff: int
    + max_clusters: int
    + n_clusters: int
    + ratio_largest: float
    + ratio_noise: float
    + execution_time: float
}

class ClusterParameters {
    + radius_cutoff: float
    + cnn_cutoff: int
    + current_start: int
    + dict to_dict()
}

class Labels {
    + labels
    + consider
    + consider_set
    + meta: dict
    + dict to_mapping()
    + set to_set()
    + sort_by_size()
}

abstract class Neighbours {
  + n_points: int
  + {abstract} assgin(member: int)
  + {abstract} reset()
  + {abstract} bool enough(member_cutoff: int)
  + {abstract} int get_member(index: int)
  + {abstract} bool contains(member: int)
}

class NeighboursExtVector

Neighbours <|.. NeighboursExtVector

abstract class InputData {
  + n_points : int
  + data
  + meta: dict
  + {abstract} get_subset(indices: Container)
}

abstract class InputDataComponents {
  + n_dim: int
  + {abstract} float get_component(point: int, dim: int)
}

abstract class InputDataPairwiseDistances {
  + {abstract} float get_distance(point_a: int, point_b: int)
}

abstract class InputDataPairwiseDistancesComputer {
  + {abstract} compute_distances()
}

abstract class InputDataNeighbourhoods {
  + {abstract} int get_n_neighbours(point: int)
  + {abstract} int get_neighbour(point: int, member: int)
}

abstract class InputDataNeighbourhoodsComputer {
  + {abstract} compute_neighbourhoods()
}

InputData <|-- InputDataComponents
InputData <|-- InputDataPairwiseDistances
InputData <|-- InputDataNeighbourhoods
InputDataNeighbourhoods <|-- InputDataNeighbourhoodsComputer
InputDataPairwiseDistances <|-- InputDataPairwiseDistancesComputer

abstract class Metric {
  + {abstract} calc_distance(index_a: int, index_b: int, ...)
  + {abstract} calc_distance_other(index_a: int, index_b: int, ...)
}

abstract class NeighboursGetter {
  + is_sorted: bool
  + is_selfcounting: bool
  + _distance_getter: DistanceGetter
  + _metric: Metric
  + {abstract} get(index: int, ...)
  + {abstract} get_other(index: int, ...)
}

abstract class DistanceGetter {
  + {abstract} float get_single(index_a: int, index_b: int ...)
  + {abstract} float get_single_other(index: int, index_b: int, ...)
}

abstract class SimilarityChecker {
  + _distance_getter: DistanceGetter
  + _metric: Metric
  + {abstract} check(neighbours_a: Neighbours, neighbours_b: Neighbours, ...)
}

abstract class Queue {
  + {abstract} push()
  + {abstract} pop()
  + {abstract} is_empty()
}

abstract class Fitter {
  + _neighbours_getter: NeighboursGetter
  + _neighbours: Neighbours
  + _neighbour_neighbours: Neighbours
  + _similarity_checker: SimilarityChecker
  + _queue: Queue
  + {abstract} fit(input_data: InputData, labels: Labels, cluster_params: ClusterParameters)
}

abstract class Predictor {
  + _neighbours_getter: NeighboursGetter
  + _neighbours: Neighbours
  + _neighbour_neighbours: Neighbours
  + _similarity_checker: SimilarityChecker
  + _queue: Queue
  + {abstract} predict(input_data: InputData, other: InputData, ...)
}

Clustering "*" o-- "1" InputData
Clustering "*" o-- "1" Fitter
Clustering "*" o-- "1" Predictor
Clustering "*" o-- "1" Labels
Clustering "*" o-- "1" Summary

Clustering --> Record : creates

NeighboursGetter "*" o-- "1" DistanceGetter
NeighboursGetter --> InputData : queries
NeighboursGetter --> Neighbours : assigns
NeighboursGetter --> ClusterParameters : uses

DistanceGetter --> InputData : queries
DistanceGetter "*" o-- "1" Metric

SimilarityChecker "*" o-- "1" DistanceGetter
SimilarityChecker --> Neighbours : checks
SimilarityChecker --> ClusterParameters : uses

Metric --> InputData : queries

Fitter "*" o-- "1" NeighboursGetter
Fitter "*" o-- "0..2" Neighbours
Fitter "*" o-- "1" SimilarityChecker
Fitter "*" o-- "1" Queue
Fitter --> Labels : manipulates

Predictor "*" o-- "1" NeighboursGetter
Predictor "*" o-- "0..2" Neighbours
Predictor "*" o-- "1" SimilarityChecker
Predictor "*" o-- "1" Queue
Predictor --> Labels : manipulates

Summary "*" -- "*" Record : stores

@enduml