__docformat__ = "restructuredtext en"
__author__ = "Jan-Oliver Joswig"
__copyright__ = "Copyright 2019, Biomolecular Dynamics Group, FU Berlin"
__credits__ = ["Jan-Oliver Joswig", "Oliver Lemke", "Bettina G. Keller"]
__license__ = "GPL"
__version__ = "0.1"
__maintainer__ = "Jan-Oliver Joswig"
__email__ = "jan DOT joswig AT fu-berlin DOT de"
__status__ = "Development"